version: '3.3'

services:
  laravel:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - laravel-storage:/var/www/html/storage
      - laravel-bootstrap-cache:/var/www/html/bootstrap/cache
    networks:
      - app-network

  vue:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./resources/js:/app/resources/js
      - ./public:/app/public
      - /node_modules
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  laravel-storage:
  laravel-bootstrap-cache:
