version: '3.3'

services:
  laravel:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    networks:
      - app-network

  vue:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./resources/js:/app/resources/js
      - ./public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
