name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ${{ secrets.VPS_PROJECT_DIR }} &&
            echo '${{ secrets.ENV }}' > .env &&
            git config --global --add safe.directory ${{ secrets.VPS_PROJECT_DIR }} &&
            git fetch --all &&
            git reset --hard origin/develop &&
            docker compose down &&
            docker compose stop &&
            docker compose rm &&
            COMPOSE_BAKE=true docker compose up -d --build
          "
